# Generated by hand for Farm attributes sync
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Human-readable address or region name', max_length=255),
        ),
        migrations.AddField(
            model_name='farm',
            name='crop',
            field=models.CharField(default='Wheat', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='area',
            field=models.CharField(default='0 ha', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='health',
            field=models.CharField(default='healthy', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='last_scan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='planted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
